from pathlib import Path
import json,hashlib
ROOT=Path(r'D:\codex\CodexWork\clash');BASE=ROOT/'work'/'batch5'/'20260926-1535-baseline';OUT=BASE/'vision_audit';events=[json.loads(x)for x in (BASE/'events.jsonl').read_text(encoding='utf8').splitlines()if x.strip()]
def evidence(i):
    e=events[i];v=e['captured_evidence']['evidence_before'];return {'index':i,'source_line':e['capture_source_line'],'time':e['time'],'battle':e['battle'],'frozen_path':v['frozen_path'],'sha256':v['expected_sha256']}
report={'status':'FAIL','reason':'Two clear visual/decision defects in battle 13; wins are not the pass gate.','session':'20260926-150126','battles':[12,13,14,15,16],'events':277,'verified_evidence_references':457,'hash_mismatches':0,'results_visually_checked':{'12':'loss 1:3','13':'loss 1:3','14':'win 2:1','15':'win 2:1','16':'loss 0:2'},'screen_unknown_review':'7 frames are matchmaking/loading/battle-intro transitions, not a stuck reward page.','reward_popup_observed':False,'plays':180,'confirmed':172,'unconfirmed':8,'confirmation_review':'Unconfirmed actions do not become successes; low-cost regeneration/card transition and battle-end frames appear among them. No extra blocking claim solely from these eight flags.','issues':[{'id':'ordinary_balloon_unknown','severity':'P1','evidence':[evidence(53),evidence(54)],'finding':'Visible ordinary balloon at (301,317) over our right tower was unknown; left Hog and then Log were chosen. This is not evidence of an empty/safe lane.'},{'id':'friendly_tower_trim_false_enemy','severity':'P1','evidence':[evidence(54)],'finding':'False enemy (314,381) comes from repaired mask bbox (310,361,8,9) on friendly right-tower artwork, not an enemy level plaque. Numeral similarity is 0.146.'}],'additional_blocking_visual_findings':[],'scope':'All 265 play/observe primary frames reviewed in contact sheets; five outcomes reviewed at full resolution; eight unconfirmed actions inspected before/after; seven transition frames inspected. This is not an exhaustive ground-truth label set for every unit.'}
(OUT/'AUDIT.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf8')
fingerprints={}
for name in ('pyclashbot/detection/cn_battle_cues.py','pyclashbot/detection/cn_threats.py','pyclashbot/detection/reference_images/cn_threats/manifest.json'):
    fingerprints[name]=hashlib.sha256((ROOT/'py-clash-bot'/name).read_bytes()).hexdigest()
(OUT/'candidate-hashes.json').write_text(json.dumps(fingerprints,indent=2),encoding='utf8');print(json.dumps(fingerprints,indent=2))
